# apimatic_calculator
#
# This file was automatically generated by APIMATIC
# v3.0 ( https://www.apimatic.io ).

module ApimaticCalculator
  # Possible operators are sum, subtract, multiply, divide
  class OperationTypeEnum
    OPERATION_TYPE_ENUM = [
      # TODO: Write general description for SUM
      SUM = 'SUM'.freeze,

      # TODO: Write general description for SUBTRACT
      SUBTRACT = 'SUBTRACT'.freeze,

      # TODO: Write general description for MULTIPLY
      MULTIPLY = 'MULTIPLY'.freeze,

      # TODO: Write general description for DIVIDE
      DIVIDE = 'DIVIDE'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OPERATION_TYPE_ENUM.include?(value)
    end

    def self.from_value(value, default_value = SUM)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'sum' then SUM
      when 'subtract' then SUBTRACT
      when 'multiply' then MULTIPLY
      when 'divide' then DIVIDE
      else
        default_value
      end
    end
  end
end
